import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Locale, i18n } from "../../../i18n.config";

import Navbar from "@/sections/nav/navbar";
import QueryProvider from "@/provider/QueryClientProvider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { estedad, geistMono, geistSans } from "@/tailwind/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ----------------------------------------------------------------------
export async function generateStaticParams() {
  return i18n.locales.map((locale: string) => ({ lang: locale }));
}
// ----------------------------------------------------------------------
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;

  const fontClass =
     lang === "fa"
      ? `${estedad.className}`
      : `${geistSans.variable} ${geistMono.variable} font-sans`;

  return (
    <html lang={lang}>
      <body
        className={`${fontClass} antialiased min-h-screen dark:text-[hsla(0,0%,100%,.9)] transition-colors duration-300`}
      >
        <ThemeProvider defaultTheme="dark" storageKey="theme">
          <Navbar lang={lang} />

          <div className="mt-16">
            <QueryProvider>{children}</QueryProvider>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
